# Generated by Django 4.2.7 on 2023-11-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_email_verified_user_otp_user_token_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='private_token',
        ),
    ]
