# Generated by Django 5.0.1 on 2024-01-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_posts_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
